-- Inserção de dados iniciais para teste

-- Países
INSERT INTO TB_PAIS (NOME) VALUES ('Brasil');
INSERT INTO TB_PAIS (NOME) VALUES ('Argentina');

-- Estados
INSERT INTO TB_ESTADO (NOME, ID_PAIS) VALUES ('São Paulo', 1);
INSERT INTO TB_ESTADO (NOME, ID_PAIS) VALUES ('Rio de Janeiro', 1);

-- Cidades
INSERT INTO TB_CIDADE (NOME, ID_ESTADO) VALUES ('São Paulo', 1);
INSERT INTO TB_CIDADE (NOME, ID_ESTADO) VALUES ('Rio de Janeiro', 2);

-- Bairros
INSERT INTO TB_BAIRRO (NOME, ID_CIDADE) VALUES ('Centro', 1);
INSERT INTO TB_BAIRRO (NOME, ID_CIDADE) VALUES ('Copacabana', 2);

-- Logradouros
INSERT INTO TB_LOGRADOURO (NOME, ID_BAIRRO) VALUES ('Av. Paulista', 1);
INSERT INTO TB_LOGRADOURO (NOME, ID_BAIRRO) VALUES ('Av. Atlântica', 2);

-- Tipos de Usuário
INSERT INTO TB_TIPO_USUARIO (DESCRICAO) VALUES ('Administrador');
INSERT INTO TB_TIPO_USUARIO (DESCRICAO) VALUES ('Operador');
INSERT INTO TB_TIPO_USUARIO (DESCRICAO) VALUES ('Cidadão');

-- Usuários (senha: 123456)
INSERT INTO TB_USUARIO (NOME, EMAIL, SENHA, DATA_CADASTRO, ID_TIPO_USUARIO)
VALUES (
  'Admin Sistema',
  'admin@geoguardian.com',
  '$2a$10$Qp6F3XlNse7o8a9MnTsPmuFXAx3PWbytvFQ8yzGCdt.PU6LRRf26.',
  CURRENT_TIMESTAMP,
  1
);

INSERT INTO TB_USUARIO (NOME, EMAIL, SENHA, DATA_CADASTRO, ID_TIPO_USUARIO)
VALUES (
  'João Silva',
  'joao@email.com',
  '$2a$10$Qp6F3XlNse7o8a9MnTsPmuFXAx3PWbytvFQ8yzGCdt.PU6LRRf26.',
  CURRENT_TIMESTAMP,
  3
);

-- Tipos de Área
INSERT INTO TB_TIPO_AREA (DESCRICAO) VALUES ('Barragem');
INSERT INTO TB_TIPO_AREA (DESCRICAO) VALUES ('Encosta');
INSERT INTO TB_TIPO_AREA (DESCRICAO) VALUES ('Margem de Rio');

-- Áreas de Risco
INSERT INTO TB_AREA_RISCO (NOME, ID_LOGRADOURO, ID_TIPO_AREA) VALUES ('Barragem Central SP', 1, 1);
INSERT INTO TB_AREA_RISCO (NOME, ID_LOGRADOURO, ID_TIPO_AREA) VALUES ('Encosta Copacabana', 2, 2);

-- Modelos de Sensor
INSERT INTO TB_MODELO_SENSOR (FABRICANTE, NOME, TIPO_MEDICAO) VALUES ('SensTech', 'UM100', 'Umidade');
INSERT INTO TB_MODELO_SENSOR (FABRICANTE, NOME, TIPO_MEDICAO) VALUES ('HydroGuard', 'NA300', 'Nível de Água');

-- Sensores
INSERT INTO TB_SENSOR (UUID, STATUS, ID_AREA_RISCO, ID_MODELO_SENSOR) VALUES ('UUID001', 'Ativo', 1, 1);
INSERT INTO TB_SENSOR (UUID, STATUS, ID_AREA_RISCO, ID_MODELO_SENSOR) VALUES ('UUID002', 'Ativo', 2, 2);

-- Tipos de Alerta
INSERT INTO TB_TIPO_ALERTA (DESCRICAO) VALUES ('Alerta de Enchente');
INSERT INTO TB_TIPO_ALERTA (DESCRICAO) VALUES ('Alerta de Deslizamento');

-- Alertas
INSERT INTO TB_ALERTA (NIVEL_RISCO, DATA_HORA, ID_TIPO_ALERTA, ID_AREA_RISCO)
VALUES (3, CURRENT_TIMESTAMP, 1, 1);

INSERT INTO TB_ALERTA (NIVEL_RISCO, DATA_HORA, ID_TIPO_ALERTA, ID_AREA_RISCO)
VALUES (4, CURRENT_TIMESTAMP, 2, 2);

-- Tipos de Ocorrência
INSERT INTO TB_TIPO_OCORRENCIA (DESCRICAO) VALUES ('Enchente Confirmada');
INSERT INTO TB_TIPO_OCORRENCIA (DESCRICAO) VALUES ('Deslizamento Confirmado');
