-- Tabela de Países
CREATE TABLE TB_PAIS (
    ID_PAIS BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL
);

-- Tabela de Estados
CREATE TABLE TB_ESTADO (
    ID_ESTADO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_PAIS BIGINT NOT NULL,
    FOREIGN KEY (ID_PAIS) REFERENCES TB_PAIS(ID_PAIS)
);

-- Tabela de Cidades
CREATE TABLE TB_CIDADE (
    ID_CIDADE BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_ESTADO BIGINT NOT NULL,
    FOREIGN KEY (ID_ESTADO) REFERENCES TB_ESTADO(ID_ESTADO)
);

-- Tabela de Bairros
CREATE TABLE TB_BAIRRO (
    ID_BAIRRO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_CIDADE BIGINT NOT NULL,
    FOREIGN KEY (ID_CIDADE) REFERENCES TB_CIDADE(ID_CIDADE)
);

-- Tabela de Logradouros
CREATE TABLE TB_LOGRADOURO (
    ID_LOGRADOURO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_BAIRRO BIGINT NOT NULL,
    FOREIGN KEY (ID_BAIRRO) REFERENCES TB_BAIRRO(ID_BAIRRO)
);

-- Tabela de Tipos de Usuário
CREATE TABLE TB_TIPO_USUARIO (
    ID_TIPO_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- Tabela de Usuários
CREATE TABLE TB_USUARIO (
    ID_USUARIO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    SENHA VARCHAR(255) NOT NULL,
    DATA_CADASTRO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_TIPO_USUARIO BIGINT NOT NULL,
    FOREIGN KEY (ID_TIPO_USUARIO) REFERENCES TB_TIPO_USUARIO(ID_TIPO_USUARIO)
);

-- Tabela de Tipos de Área
CREATE TABLE TB_TIPO_AREA (
    ID_TIPO_AREA BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- Tabela de Áreas de Risco
CREATE TABLE TB_AREA_RISCO (
    ID_AREA_RISCO BIGINT AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ID_LOGRADOURO BIGINT NOT NULL,
    ID_TIPO_AREA BIGINT NOT NULL,
    FOREIGN KEY (ID_LOGRADOURO) REFERENCES TB_LOGRADOURO(ID_LOGRADOURO),
    FOREIGN KEY (ID_TIPO_AREA) REFERENCES TB_TIPO_AREA(ID_TIPO_AREA)
);

-- Tabela de Modelos de Sensor
CREATE TABLE TB_MODELO_SENSOR (
    ID_MODELO_SENSOR BIGINT AUTO_INCREMENT PRIMARY KEY,
    FABRICANTE VARCHAR(100) NOT NULL,
    NOME VARCHAR(100) NOT NULL,
    TIPO_MEDICAO VARCHAR(100) NOT NULL
);

-- Tabela de Sensores
CREATE TABLE TB_SENSOR (
    ID_SENSOR BIGINT AUTO_INCREMENT PRIMARY KEY,
    UUID VARCHAR(100) NOT NULL,
    STATUS VARCHAR(50) NOT NULL,
    ID_AREA_RISCO BIGINT NOT NULL,
    ID_MODELO_SENSOR BIGINT NOT NULL,
    FOREIGN KEY (ID_AREA_RISCO) REFERENCES TB_AREA_RISCO(ID_AREA_RISCO),
    FOREIGN KEY (ID_MODELO_SENSOR) REFERENCES TB_MODELO_SENSOR(ID_MODELO_SENSOR)
);

-- Tabela de Tipos de Alerta
CREATE TABLE TB_TIPO_ALERTA (
    ID_TIPO_ALERTA BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);

-- Tabela de Alertas
CREATE TABLE TB_ALERTA (
    ID_ALERTA BIGINT AUTO_INCREMENT PRIMARY KEY,
    NIVEL_RISCO INT NOT NULL,
    DATA_HORA TIMESTAMP NOT NULL,
    ID_TIPO_ALERTA BIGINT NOT NULL,
    ID_AREA_RISCO BIGINT NOT NULL,
    FOREIGN KEY (ID_TIPO_ALERTA) REFERENCES TB_TIPO_ALERTA(ID_TIPO_ALERTA),
    FOREIGN KEY (ID_AREA_RISCO) REFERENCES TB_AREA_RISCO(ID_AREA_RISCO)
);

-- Tabela de Tipos de Ocorrência
CREATE TABLE TB_TIPO_OCORRENCIA (
    ID_TIPO_OCORRENCIA BIGINT AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(100) NOT NULL
);
